import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import './bones/registry' // Auto-generated by Boneyard
import App from './App.jsx'
import { initTheme } from './utils/theme'

// Initialize theme before render to prevent flash
initTheme()

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
